### ISSUE TITLE
Integrate mobile payment solution

### ISSUE THREAD

**Issue by pnull** [tankste/app#22]
Bertha had the option to pay right at the pump with your mobile phone.

At PACE, we offer open SDKs and APIs to integrate the same functionality for even more stations and much more payment schemes. The APIs could be used to implement the same user experience that Bertha offered.

Resources:
* API spec: https://developer.pace.cloud/api/fueling?version=2022-1
* Integration dochmentation: https://docs.pace.cloud
* Open source SDKs: https://github.com/pace

**Comment by markusweb** [comment]
I disagree. I don't need any payment solution. I use my credit card via mobile payment. That is enough. i don't want or need to handle payment in the app. that always means one more user account. Payment is way to complicated. you have to to accounting and billing, handling money transfer etc.,

**Comment by Fabi755** [comment]
Hey @pnull thanks for your suggestions to PACE. 

We already have an issue for that (#19) where we need to evaluate a lot of stuff. But before we include some payment we have to work on more basic features and need own backend structure.

It would be nice if you can mail me at fabian@tankste.app your contact data, that I can reach you if I start evaluating this topic. Thanks!
