### ISSUE TITLE
Apple Maps on iOS platform

### ISSUE THREAD

**Issue by Fabi755** [tankste/app#4]
Use Apple Maps instead of Google Maps on iOS/iPadOS.

To be discuss: Should we always use Apple Maps or give we iOS users the choice to switch back to Google Maps in the settings?!

**Comment by chloe-the-catgirl** [comment]
I'd like to see this, as the current Google Maps integration is kinda slow. At least on my iPhone 12 Mini which is definitely not outdated. Dunno if it's the map engine, but in comparison to Apple Maps, *tankste* feels quite sluggish ^^

Happy to help with beta testing, if wanted :)

**Comment by F3000** [comment]
Alone for privacy reasons there is no alternative to AppleMaps . 

Maybe Mapbox ?

**Comment by Fabi755** [comment]
Hey @chloe-the-catgirl let me know if this problem always exists in the coming update. You can use issue #26 for that. 

Thank you!
